### ISSUE TITLE
Max Quantity and Quantity/Cart Update 

### ISSUE THREAD

**Issue by eCroFeox** [breakerh/quantity-enabled-for-jet-booking#1]
Hi Bram, 

I just found this plugin and it is great. It is exactly what I need for my website, because my clients need to be able to book several items at the same time. **Thank you so much!**
Unfortunately I found some issues, that I want to share with you. 

I use JetBooking v3.3.2 in Woocommerce Mode, Woocommerce v8.8.3 and Elementor / Elementor Pro. 
I enabled Managed Units for each product. 

Plugin settings:
Hide datatime: enabled
Show current and available Stock: enabled
Limit quantity to max available: enabled
Cooldown time: 0
Warmup time: 0

1. Issue: 
With the Number Select Field to change the quantity, I can choose more than the maximum of units available, although "Limit quantity to max available" is enabled

2. Issue: 
If I add products to the cart and I check the cart, I can change the quantity of the products and update the cart. But the new quantity is not calculated correctly. For example, I have 4 items in my cart and I want to change it to 6 and I update the cart, the new quantity is not 6 but 9.

3. Issue:
Also in the Cart overview I can change the quantity to more than max. available items.

Overall it's a great plugin and I still do not understand, why Crocoblock was not adding this function from the beginning. 
I hope you can fix these problems. If you have more questions, feel free to get in touch with me. 

Best Regards

**Comment by breakerh** [comment]
Hello @eCroFeox ,

Thanks for letting me know! I will look into it later today.
You use the same setup as I do, so weird that the input field doesn't limit it.

The cart part is a good one, will add this! In our use case we show the quantity but don't allow them to change it there.
Will add both options and make sure calculation don't get messed up.

ps. just to be sure, on the product page what add-to-cart element do you use?
There are multiple if you use jet woo builder and have elementor pro for example :)
As far as i know they all 'listen' to the same filter to set the max but seems like I was wrong haha.

Thanks again!

**Comment by eCroFeox** [comment]
Hey Bram, 

thanks for your response. 

I use from "JetWooBuilder" the "Single Add to Cart" Widget.

Best Regards

**Comment by breakerh** [comment]
Hey @eCroFeox I've just released a new version which includes the features that didn't work as expected.

Thank you very much!

**Comment by eCroFeox** [comment]
It works now perfectly. Thank you very much!
